/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wander_jni_JNITest */

#ifndef _Included_com_wander_jni_JNITest
#define _Included_com_wander_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wander_jni_JNITest
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wander_jni_JNITest_test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
